class ConnectionDatabaseException(Exception):
    def __init__(self):
        pass
